### ISSUE TITLE
FK_admin_abk  einheitlich im DUMP und einlese funktion?

### ISSUE THREAD

**Issue by Rentsch** [Greif5/QSL-DB#10]
Im aktuellen Dump ist  das attribut "FK_admin_abk" in der tabelle "qsl_broadcaster" und "qsl_site" unterschiedlich. Einmal mit großém A einmal mit kleinem a. Das führt dazu das meine funnktion in  table_show_entry.php nicht richtig funktioniert.
Prüfen ob das auch in irgenwelchen andern einlese funktionen fehlerhaft ist.

**Comment by Greif5** [comment]
Ich hab jetzt alle Attribute in der Datenbank klein geschrieben.
Nur FK bleibt groß als Hinweis.
https://github.com/Greif5/QSL-DB/commit/a3055abbdadb06fea53a299a98c2824cf6863fa6
Wahrscheinlich müssen wir jetzt noch die Scripte anpassen.

**Comment by Greif5** [comment]
art auch noch in abk geändert.
f83c0fb9be0df85989fa2052f9ac8f95f6c6fe5a
