### ISSUE TITLE
Datenbank vereinheitlichen

### ISSUE THREAD

**Issue by Greif5** [Greif5/QSL-DB#14]

**Comment by Rentsch** [comment]
- Alle Namen vereinheitlichen (tabllennamen, attribute und Fremdschlüssel)
- Alle Primärschlüssel gleich name (macht es päter einfach einen select abzufragen.
- Attribut Fk_verfication_ABK  da fehlt ein "i".

**Comment by Greif5** [comment]
2. Willst du das ernsthaft so? Fände das viel zu unübersichtlich, vorallem weil jetzt alle Tabellen "abk"
als PriKey haben, bis auf qsl_karte, da ist es ID.
3. 114d6e90428b29b8c40a74b2a96dedd5c5f4282e

**Comment by Greif5** [comment]
1. cfd3b939513ddb77506de9d202eb34f62005cd2c

**Comment by Greif5** [comment]
Hab "dauer" übersehen
0a82fc493e960d2651f38b173f087773e09386ef
