### ISSUE TITLE
DB: Update ER-Diagramm

### ISSUE THREAD

**Issue by Rentsch** [Greif5/QSL-DB#18]

**Comment by Rentsch** [comment]
Legende HInzufügen.

**Comment by Greif5** [comment]
Legende fehlt noch.
https://github.com/Greif5/QSL-DB/commit/41b98d3e844a8c58f353a2bfb3faf5291db4315a

**Comment by Greif5** [comment]
ER hat ne Legende bekommen
https://github.com/Greif5/QSL-DB/commit/2f335729746e7bbd55f84165c84f97308aedddbe

**Comment by Greif5** [comment]
qsl_card Band rausnehmen

**Comment by Greif5** [comment]
Ist fertig
