### ISSUE TITLE
Lecker Schmecker Cookies.

### ISSUE THREAD

**Issue by Rentsch** [Greif5/QSL-DB#22]

**Comment by Greif5** [comment]
Bin dabei
https://github.com/Greif5/QSL-DB/commit/2fa7667d2d25a7681f0a967f0ef5ab01b32d395f

**Comment by Greif5** [comment]
Cookie Funktionen hinzugefügt.
https://github.com/Greif5/QSL-DB/commit/f066c213a8f9df9adb19fd8bb14eb6927f21fbd6

**Comment by Greif5** [comment]
Cookies sollten inzwischen funktionieren.
