### ISSUE TITLE
Buttons in Detailansicht überlagern sich nicht richtig

### ISSUE THREAD

**Issue by Mettzilla** [Greif5/QSL-DB#37]
Browserfenster bisschen vekleinert :

![buttons_lagern_ubereinander](https://user-images.githubusercontent.com/33263631/37875709-6a58c18c-3043-11e8-89d5-82330e1abe12.png)

So ist korrekt : 
![buttons_lagern_ubereinander_korrekt](https://user-images.githubusercontent.com/33263631/37875710-6a70115c-3043-11e8-916a-e3cc2136e482.png)

**Comment by Greif5** [comment]
Hatten wir das inzwischen behoben / als unfixbar erklärt?
@Mettzilla
