### ISSUE TITLE
Gültige Frequenzen werden bei der Eingabe "Add Card" nicht akzeptiert

### ISSUE THREAD

**Issue by Mettzilla** [Greif5/QSL-DB#39]
Problem 1 : 
Nur 100er Schritte werden akzeptiert. 

Problem 2 : 
Es müssen aber folgende Frequenzen abgespeichert werden können. 

500 = 005000 in der DB mit den führenden Nullen
500.5 = 005005 
1000.1 s.o.
12340.5 

Als Basis müssen immer 6 Ziffern genommen werden . Die Frequenz kann also Leading Zeros enthalten.
Aus der Textdatei mit dem derzeitigem Format würde die Nachkommastelle nur mit 6 Ziffern auf der Schnittstelle zum Funkgerät akzeptiert werden.

**Comment by Greif5** [comment]
Problem haben wir doch behoben oder?
@Mettzilla kann geschlossen werden?
