### ISSUE TITLE
neue Funktionen schmeißen Fehlermeldung

### ISSUE THREAD

**Issue by Rentsch** [Greif5/QSL-DB#9]
Die Änderung aus Commit: https://github.com/Greif5/QSL-DB/commit/1fba1ce5605b60f82bcda50c5a3170aaaa396fda führen dazu, das die Datei nicht ausführbar ist.

**Comment by Greif5** [comment]
Ich hatte überall Semikolons vergessen.
7cb7dc0
Bei der Gelegenheit hab ich gleich die Tabellenattribute gefixt.
01e4ac7
